### PR TITLE
Add my brand icon image, shortbio and social link

### PR DESCRIPTION
**Pull request by giulianolatini**

### CODE REVIEW

**Review by MattVSTS — CHANGES_REQUESTED** [review]
Please change the Eng bio with:

I have almost thirty years of experience in IT, on software used for university research and about the Italian public administration environment. 
Since 2000 I manage IT operations remotely, and in the last five years I got interested in the cultural side of DevOps. My work taught me that every problem has a solution, but technology does not solve all of the issues.

**Comment by giulianolatini** [comment]
Ok, I made the change request. Thank's for you time.

**Review by giulianolatini — COMMENTED** [review]
Ok, I made the change request. Thank's for you time.

**Comment by giulianolatini** [comment]
I see branch Author/* . Close this request and I pulling request to Authors/giulianolatini's branch

**Pull request closed without merging**
