### PR TITLE
New post/article for reducing the gap between Dev and Ops with azuredevops

### LINKED ISSUE #28: Post: Reducing the gap between operations and development using Azure DevOps
Adding a new article:

"Reducing such a gap is possible using a combination of DevOps culture and the right tools. We will see hereafter how my organization tries to do so using Azure DevOps." 

Article for our website (EU).
Pull request will follow.

### PR DESCRIPTION
**Pull request by suxstellino**
Article/Post for "reducing the gaap between Dev and Ops with azuredevops". 
Images and article added.

issue #28

### CODE REVIEW

**Review by MattVSTS — COMMENTED** [review]
A few Italianisms to look after, but it's a good start. It would benefit from some paragraph spacing.

I also cannot understand this sentence: "Moreover, we're isolating the management maintaining the relationships between work items that reside on different boards."

**Comment by suxstellino** [comment]
It should have meant "Abbiamo isolato la parte di gestione (ad esempio per dipartimento) visto che sono stati creati backlog indipendenti tra loro. Tuttavia, mantenendo le relazioni tra gli elementi è possibile avere comunque sinergia, seppure gli item siano su board/iterazioni diverse"

**Comment by giuliov** [comment]
A major issue: you reference the images using `/static/images/...` while the correct path is `/images/...`.

My recommendation is to have all files in a single folder (see #6) for three reasons:
 - preview using either `hugo server --buildFutures` or the editor (e.g. VSCode Markdown) works smoothly;
 - simpler to use for authors;
- Hugo considers any file in the same directory as the page as a bundle, which can be leveraged by themes and custom layouts.

`/images` should be used mostly for site-wide content.

You need a few changes:
 1. create a directory with the same name as the `.md` file;
 2. move the post in the new directory `git mv content/post/suxstellino/azdos-reducing-gap-between-dev-and-ops.en.md content/post/suxstellino/azdos-reducing-gap-between-dev-and-ops/index.en.md`
 3. move the images in the directory `git mv static/images/suxstellino/post01-* content/post/suxstellino/azdos-reducing-gap-between-dev-and-ops/`
 4. fix the references in the post (find `'/static/images/suxstellino/'` and replace with `''`)

**Comment by suxstellino** [comment]
@giuliov resources moved. Please check.

**Comment by giuliov** [comment]
ok for me

**Comment by suxstellino** [comment]
I'll switch the publish date between the new post (coming in a day) and this one, that will be scheduled the next Wednesday.

**Pull request merged**
